# Generated by Django 4.2.1 on 2023-06-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarsquadapi', '0003_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='student',
        ),
    ]
