# Generated by Django 4.2.1 on 2023-06-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarsquadapi', '0005_classroom_remove_teacher_schoolclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='scholarsquadapi.classroom'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scholarsquadapi.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='scholarsquadapi.classroom'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_by_teacher', to='scholarsquadapi.teacher'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarsquadapi.answer'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarsquadapi.question'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to='scholarsquadapi.studentquiz'),
        ),
        migrations.AlterField(
            model_name='studentquiz',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_quizzes', to='scholarsquadapi.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='scholarsquadapi.school'),
        ),
    ]
