# Generated by Django 4.2.1 on 2023-06-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarsquadapi', '0006_student_classroom_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.ManyToManyField(related_name='teachers', to='scholarsquadapi.classroom'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='scholarsquadapi.school'),
        ),
    ]
