# Generated by Django 4.2.1 on 2023-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarsquadapi', '0008_remove_student_classroom_student_classrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(related_name='students', to='scholarsquadapi.classroom'),
        ),
    ]
