# Generated by Django 4.2.1 on 2023-06-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarsquadapi', '0009_remove_classroom_teacher_alter_student_classrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='classroom',
            new_name='classrooms',
        ),
    ]
