# Generated by Django 4.2.1 on 2023-06-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarsquadapi', '0010_rename_classroom_teacher_classrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='scholarsquadapi.teacher'),
        ),
    ]
