# Generated by Django 4.2.1 on 2023-06-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarsquadapi', '0011_remove_teacher_classrooms_classroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.CharField(default='this is my description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='roomNumber',
            field=models.CharField(default='101A', max_length=10),
            preserve_default=False,
        ),
    ]
