from .answer import Answer
from .question import Question
from .quiz import Quiz
from .school import School
from .schoolClass import SchoolClass 
from .student import Student
from .studentAnswer import StudentAnswer
from .studentQuiz import StudentQuiz
from .teacher import Teacher 